name: Linux ARM64 installer on Python 3.8

on: [push, pull_request]

jobs:
  testactions_job:
    runs-on: ubuntu-latest
    name: Test

    strategy:
      matrix:
        include:
          # The full matrix of Dockerfiles would be extensive, so just
          # cover each arch and OS at least once.
          - arch: aarch64
            distro: archarm_latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    
