name: Linux ARM64 installer on Python 3.8

on:
  push:
    branches:
      - pools-release
    tags:
        - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: Linux ARM64 installer on Python 3.8
    runs-on: ARM64

    # Run steps on a matrix of 3 arch/distro combinations
    strategy:
      matrix:
        python-version: [3.8]
        include:
          - arch: aarch64
            distro: archarm_latest     

    steps:
    - name: Cancel previous runs on the same branch
      if: ${{ github.ref != 'refs/heads/main' }}
      uses: styfle/cancel-workflow-action@0.9.0
      with:
        access_token: ${{ github.token }}

    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Run commands
      id: runcmd
      run: |
        uname -a
        echo ::set-output name=uname::$(uname -a)
            
    - name: Get the output
      run: |
        echo "The uname output was ${{ steps.runcmd.outputs.uname }}"
